name: Feedback Proxy
on: [workflow_dispatch]

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitHub API
        env:
          GH_TOKEN: ${{ secrets.GH_FEEDBACK_TOKEN }}
        run: |
          curl -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/clarklibraries/feedback-system/issues
