name: Update Feedback

on:
  repository_dispatch:
    types: [update-feedback]

jobs:
  update-feedback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update feedback
        run: |
          FEEDBACK_TYPE=${{ github.event.client_payload.feedback }}
          jq --arg type "$FEEDBACK_TYPE" '.feedback[$type] += 1' data/feedback.json > temp.json && mv temp.json data/feedback.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/feedback.json
          git commit -m "Update feedback count"
          git push
